### ISSUE TITLE
"Rejected" label is missing in UI

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/gov-app#16]
https://gov.nation3.org/proposals

> <img width="784" alt="Screen Shot 2022-10-24 at 5 28 12 PM" src="https://user-images.githubusercontent.com/95955389/197494940-3bb1edde-efb1-4409-bba4-f48feaace792.png">

> <img width="768" alt="Screen Shot 2022-10-24 at 5 28 22 PM" src="https://user-images.githubusercontent.com/95955389/197494952-be488beb-2c0a-4752-991b-d29e62bfb911.png">

**Comment by developerfred** [comment]
@aahna-ashina This issue has been fixed here https://github.com/nation3/gov-app/commit/f424a5810caf675f7b06ab60c4b4c55582ec1995 by @luisivan  

close plis
