### ISSUE TITLE
Remove "test" from input fields

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/gov-app#4]
https://gov.nation3.org/proposals/create

> <img width="900" alt="Screen Shot 2022-08-12 at 2 39 41 PM" src="https://user-images.githubusercontent.com/95955389/184298576-2c40b4a2-dcb9-4fdd-a42b-01231fd0dde2.png">

**Comment by luisivan** [comment]
The form autosaves the values, so most probably you wrote "test" and it got saved?

**Comment by aahna-ashina** [comment]
> The form autosaves the values, so most probably you wrote "test" and it got saved?

Oh, yes, I think I did that a few days ago 😂

Closing this issue.
